---
- name: "creating systemd unit for {{ service_name }}"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: 0644
  register: container_service
- name: "systemd unit {{ service_name }} changed: reloading daemons"
  ansible.builtin.systemd:
    daemon_reload: true
  when: container_service.changed
