---
- name: "creating systemd unit for {{ service_name }}"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: 0644
  register: current_service
- name: "systemd unit {{ service_name }} changed: reloading daemons"
  ansible.builtin.systemd:
    daemon_reload: true
  when: current_service.changed
- name: "notifying service changes?"
  when: ( notify is defined )
  changed_when: current_service.changed
  debug:
    msg: "notifying service changes"
  notify: "{{ notify }}"
