---
- name: "{{ service_name }} | create docker service"
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
  register: container_service
- name: "{{ service_name }} | systemctl daemon reload"
  ansible.builtin.systemd:
    daemon_reload: true
  when: container_service.changed