---
- name: make journald persistent (/var/log/journal)
  file:
    dest: "/var/log/journal"
    state: directory
    owner: root
    mode: 0755
  notify: "restart journald"
- name: allow 1000 messages per second on journald
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^ *RateLimitInterval='
    line: 'RateLimitInterval=1s'
  notify: "restart journald"
- name: set journald forward to Syslog => {{ forward_to_syslog }}
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^ *ForwardToSyslog='
    line: 'ForwardToSyslog={{ forward_to_syslog }}'
  notify: "restart journald"
