---
- name: ensuring /var/log/journal exists
  ansible.builtin.file:
    dest: "/var/log/journal"
    state: directory
    owner: root
    mode: 0755
  notify: "restart journald"
- name: configuring journald
  when: (configuration is defined)
  copy:
    mode: 0644
    dest: /etc/systemd/journald.conf
    content: "{{ configuration }}"
  notify: "restart journald"
