galaxy_info:
  author: optionfactory
  description: aws - centos base configuration (7)
  company: optionfactory
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Centos
    versions:
    - 7
  galaxy_tags: []
dependencies: []
