---
- name: Ubuntu
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20
  block:
    - name: Add docker repo key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true
    - name: Add docker repository
      ansible.builtin.apt_repository:
        filename: dockerrepo
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: Debian
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11
  block:
    - name: Add docker repo key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true
    - name: Add docker repo
      ansible.builtin.apt_repository:
        filename: dockerrepo
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true
- name: Configure http/https proxy for docker service
  when: ((docker_http_proxy is defined) and (docker_http_proxy|length > 0)) or ((docker_https_proxy is defined) and (docker_https_proxy|length > 0))
  block:
    - name: Create docker service configuration directory
      ansible.builtin.file:
        state: directory
        path: /etc/systemd/system/docker.service.d
        owner: root
        mode: '0755'
    - name: Create docker proxy server configuration
      ansible.builtin.template:
        src: files/http-proxy.conf.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        owner: root
        mode: '0644'
    - name: Reload configuration and restart docker service
      ansible.builtin.systemd_service:
        name: docker.service
        daemon_reload: true
        state: restarted
- name: Ensure that docker group is present
  ansible.builtin.group:
    name: docker
    state: present
- name: Ubuntu user
  ansible.builtin.user:
    name: ubuntu
    append: true
    groups: docker
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20
- name: Debian user
  ansible.builtin.user:
    name: admin
    append: true
    groups: docker
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11
- name: Ensure base services are started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
