---
- name: ubuntu
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20
  block:
  - name: add docker repo key
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      dest: /etc/apt/trusted.gpg.d/docker.asc
      mode: '0644'
      force: true
  - name: add docker repo
    ansible.builtin.apt_repository:
      filename: dockerrepo
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
- name: debian
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11
  block:
  - name: add docker repo key
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/debian/gpg"
      dest: /etc/apt/trusted.gpg.d/docker.asc
      mode: '0644'
      force: true
  - name: add docker repo
    ansible.builtin.apt_repository:
      filename: dockerrepo
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
- name: update apt cache
  shell: apt update
- name: install docker-ce
  apt:
    name: docker-ce
    state: present
- group:
    name: docker 
    state: present
- name: ubuntu user
  user:
    name: ubuntu
    append: yes
    groups: docker
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20
- name: debian user
  user:
    name: admin
    append: yes
    groups: docker
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 11
- name: ensure base services are started
  service:
    name: docker
    state: started
    enabled: yes