galaxy_info:
  author: optionfactory
  description: centralized logging with journal upload
  company: optionfactory
  license: BSD
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - bionic
    - focal
  galaxy_tags: []
dependencies: []
