---
- name: Converge
  hosts: all
  become: true
  vars:
    a_var: "a_var_value"
    images_version: 229
  tasks:
    - name: Test the services.bundle plugin
      optionfactory.services.bundle:
        name: testapp
        container:
          image: "optionfactory/debian13-jdk21-keycloak2:{{ images_version }}"
          network: testapp
          ip: "172.18.0.11"
          env:
            TEST_VAR: "{{ a_var }}"
          mounts:
            - source: /opt/testapp/conf
              target: /opt/testapp/conf
              readonly: true
            - source: /opt/testapp/bin
              target: /opt/testapp/bin
              when: false
        dirs:
          - dest: /opt/testapp/
          - dest: /opt/testapp/bin
          - dest: /opt/testapp/conf
        files:
          - dest: /opt/testapp/bin/test-app.jar
            src: testapp.jar
          - dest: /opt/testapp/conf/configuration.properties
            content: >
              key=value
              key2={{ a_var }}

    - name: Test the services.service plugin with a command service
      optionfactory.services.service:
        name: testapp-command
        command:
          exec: /usr/bin/sleep
          args: infinity
