galaxy_info:
  author: optionfactory
  description: Creates SSH config from ansible inventory
  company: optionfactory
  license: BSD-3-Clause
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
  galaxy_tags: []
dependencies: []
