- name: Example usage of legopfa
  hosts:
    - 127.0.0.1
  connection: local
  tasks:
    - name: Can configure legopfa service and timer
      ansible.builtin.include_role:
        name: legopfa
      vars:
        container_name: "nginx-project"
