namespace: optionfactory
name: services
version: 2.0.2
readme: README.md
authors:
  - Multiple <info@optionfactory.net>
description: Handles services configuration
license:
  - BSD-3-Clause
dependencies: {}
repository: http://github.com/optionfactory/ansible-optionfactory-collections
documentation: http://github.com/optionfactory/ansible-optionfactory-collections
homepage: http://github.com/optionfactory/ansible-optionfactory-collections
issues: http://github.com/optionfactory/ansible-optionfactory-collections
