- hosts:
    - 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: "can install docker with docker.install"
      include_role:
        name: install
    - name: "can configure docker groups and users"
      include_role:
        name: users
    - name: "can install a docker.service"
      include_role:
        name: service
      vars:
        service_name: debian-project
        service_args: >
          debian:12
