- name: "Example usage of docker.service"
  hosts:
    - 127.0.0.1
  connection: local
  tasks:
    - name: "Can install a docker.service"
      ansible.builtin.include_role:
        name: service
      vars:
        notify_key: debian-project-service-changed
        service_name: debian-project
        service_args: >
          debian:12
    - name: Globals
      ansible.builtin.debug:
        var: vars['container_service']
    - name: "Can install docker with docker.install"
      ansible.builtin.include_role:
        name: install
    - name: "Can configure docker groups and users"
      ansible.builtin.include_role:
        name: users
    - name: "Can install a docker.service"
      ansible.builtin.include_role:
        name: service
      vars:
        notify_key: debian-project-service-changed
        service_name: debian-project
        service_args: >
          debian:12
  handlers:
    - name: Debian-project-service-changed
      listen: debian-project-service-changed
      ansible.builtin.debug:
        msg: "debian project changed"
