---
- name: disable requiretty
  lineinfile:
    dest: /etc/sudoers
    regexp: 'Defaults.*requiretty'
    state: absent
- name: install EPEL
  yum:
    name: "epel-release"
    state: present
    update_cache: yes
- name: install things
  yum:
    name: ['bash-completion', 'ca-certificates', 'curl', 'rsync', 'python-pip']
    state: present
    update_cache: yes
- name: make journald persistent (/var/log/journal)
  file:
    dest: "/var/log/journal"
    state: directory
    owner: root
    mode: 0700
  notify: "restart journald"
- name: allow 1000 messages per second on journald
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^ *RateLimitInterval='
    line: 'RateLimitInterval=1s'
  notify: "restart journald"
- name: install PS1
  copy:
    dest: /etc/profile.d/ps1.sh
    src: roles/centos-aws/files/ps1.sh
