---
- name: Ensuring group "docker-machines" exists
  ansible.builtin.group:
    state: present
    name: docker-machines
    gid: 950
- name: Ensuring user "docker-machines" exists
  ansible.builtin.user:
    state: present
    name: docker-machines
    system: true
    create_home: false
    home: /
    shell: /usr/sbin/nologin
    uid: 950
    group: docker-machines
- name: Ensuring user is in "docker" group
  ansible.builtin.user:
    name: "{{ user | default(ansible_facts['env'].SUDO_USER) }}"
    append: true
    groups: docker
- name: Ensuring ansible_user is in docker-machines group
  ansible.builtin.user:
    name: "{{ user | default(ansible_facts['env'].SUDO_USER) }}"
    append: true
    groups: docker-machines
