---
- name: ensuring group "docker-machines" exists
  group:
    state: present
    name: docker-machines
    gid: 950
- name: ensuring user "docker-machines" exists
  user:
    state: present
    name: docker-machines
    system: true
    create_home: false
    home: /
    shell: /usr/sbin/nologin
    uid: 950
    group: docker-machines
- block:
    - name: ensuring ansible_user is in "docker" group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        append: true
        groups: docker
      when: ( user is undefined )
    - name: ensuring custom user is in "docker" group
      user:
        name: "{{ user }}"
        append: true
        groups: docker
      when: ( user is defined )
- block:
    - name: ensuring ansible_user is in docker-machines group
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        append: true
        groups: docker-machines
      when: ( user is undefined )
    - name: ensuring ansible_user is in docker-machines group
      user:
        name: "{{ user }}"
        append: true
        groups: docker-machines
      when: ( user is defined )
