---
- name: ensuring group "docker-machines" exists
  group:
    state: present
    name: docker-machines
    gid: 950
- name: ensuring user "docker-machines" exists
  user:
    state: present
    name: docker-machines
    system: true
    create_home: false
    home: /usr/sbin/nologin
    uid: 950
    group: docker-machines
- name: ensuring ansible_user is in "docker" group
  user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
- name: ensuring ansible_user is in docker-machines group
  user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker-machines
